package fr.bbodin.courbedepoids;
import android.app.AlertDialog;import android.app.Fragment;import android.app.TimePickerDialog;import android.graphics.Color;import android.os.Bundle;import android.text.InputType;import android.view.Gravity;import android.view.LayoutInflater;import android.view.View;import android.view.ViewGroup;import android.widget.EditText;import android.widget.ImageView;import android.widget.LinearLayout;import android.widget.RadioButton;import android.widget.RadioGroup;import android.widget.TextView;import android.widget.Toast;import java.text.SimpleDateFormat;import java.util.ArrayList;import java.util.Calendar;import java.util.Collections;import java.util.List;import java.util.Locale;import java.util.TimeZone;
public class HistoryFragment extends Fragment{
 private LinearLayout list;private WeightDatabase db;private ImageView filterWeight,filterWater,filterSport;private boolean showWeight=true,showWater=true,showSport=true;private final SimpleDateFormat tf=new SimpleDateFormat("HH:mm",Locale.FRANCE);
 private static class Entry{String date;long time;WeightDatabase.Measurement m;WeightDatabase.WaterEvent w;WeightDatabase.SportEvent s;Entry(WeightDatabase.Measurement x){date=x.date;time=x.measuredAt;m=x;}Entry(WeightDatabase.WaterEvent x){date=x.date;time=x.createdAt;w=x;}Entry(WeightDatabase.SportEvent x){date=x.date;time=x.createdAt;s=x;}}
 @Override public View onCreateView(LayoutInflater i,ViewGroup c,Bundle b){return i.inflate(R.layout.activity_history,c,false);}
 @Override public void onViewCreated(View v,Bundle b){super.onViewCreated(v,b);db=new WeightDatabase(getActivity());list=v.findViewById(R.id.history_list);LinearLayout f=new LinearLayout(getActivity());f.setOrientation(LinearLayout.HORIZONTAL);f.setGravity(Gravity.CENTER_VERTICAL);f.setPadding(dp(12),dp(4),dp(12),dp(4));f.setBackgroundResource(R.drawable.bg_card);filterWeight=filter(R.drawable.ic_scale,"Afficher ou masquer les mesures de poids");filterWater=filter(R.drawable.ic_water,"Afficher ou masquer les mesures d’eau");filterSport=filter(R.drawable.ic_sport,"Afficher ou masquer les mesures de sport");f.addView(filterWeight,new LinearLayout.LayoutParams(0,dp(48),1));f.addView(filterWater,new LinearLayout.LayoutParams(0,dp(48),1));f.addView(filterSport,new LinearLayout.LayoutParams(0,dp(48),1));((ViewGroup)v).addView(f,1,new ViewGroup.LayoutParams(-1,-2));filterWeight.setOnClickListener(x->{showWeight=!showWeight;styleFilter(filterWeight,showWeight);render();});filterWater.setOnClickListener(x->{showWater=!showWater;styleFilter(filterWater,showWater);render();});filterSport.setOnClickListener(x->{showSport=!showSport;styleFilter(filterSport,showSport);render();});styleFilter(filterWeight,showWeight);styleFilter(filterWater,showWater);styleFilter(filterSport,showSport);render();}
 private ImageView filter(int icon,String description){ImageView v=new ImageView(getActivity());v.setImageResource(icon);v.setContentDescription(description);v.setScaleType(ImageView.ScaleType.CENTER_INSIDE);v.setPadding(dp(10),dp(10),dp(10),dp(10));v.setClickable(true);v.setFocusable(true);return v;}\n private void styleFilter(ImageView view,boolean selected){view.setAlpha(selected?1f:0.35f);view.setBackgroundColor(selected?Color.rgb(220,238,255):Color.TRANSPARENT);view.setColorFilter(selected?Color.rgb(20,123,239):Color.rgb(100,116,139));}
 @Override public void onResume(){super.onResume();if(db!=null&&list!=null)render();}
 private void render(){list.removeAllViews();List<Entry> es=new ArrayList<>();if(showWeight)for(WeightDatabase.Measurement x:db.all())es.add(new Entry(x));if(showWater)for(WeightDatabase.WaterEvent x:db.allWaterEvents())es.add(new Entry(x));if(showSport)for(WeightDatabase.SportEvent x:db.allSportEvents())es.add(new Entry(x));Collections.sort(es,(a,b)->{int n=b.date.compareTo(a.date);return n!=0?n:Long.compare(b.time,a.time);});String day=null;for(Entry e:es){if(!e.date.equals(day)){day=e.date;TextView h=new TextView(getActivity());h.setText(dateLabel(day));h.setTextSize(16);h.setTypeface(null,android.graphics.Typeface.BOLD);h.setTextColor(Color.rgb(20,36,58));h.setPadding(dp(4),dp(16),dp(4),dp(8));list.addView(h);}addRow(e);}if(es.isEmpty()){TextView t=new TextView(getActivity());t.setText("Aucune mesure pour les catégories sélectionnées.");t.setTextSize(16);t.setTextColor(Color.rgb(100,116,139));t.setGravity(Gravity.CENTER);t.setPadding(dp(12),dp(48),dp(12),0);list.addView(t);}}
 private void addRow(Entry e){LinearLayout r=new LinearLayout(getActivity());r.setOrientation(LinearLayout.HORIZONTAL);r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(dp(14),dp(12),dp(14),dp(12));r.setBackgroundResource(R.drawable.bg_card);if(e.m!=null)r.setOnClickListener(v->editWeight(e.m));else if(e.w!=null)r.setOnClickListener(v->editWater(e.w));else r.setOnClickListener(v->editSport(e.s));ImageView icon=new ImageView(getActivity());icon.setImageResource(e.m!=null?R.drawable.ic_scale:e.w!=null?R.drawable.ic_water:R.drawable.ic_sport);LinearLayout.LayoutParams ip=new LinearLayout.LayoutParams(dp(36),dp(36));ip.setMarginEnd(dp(12));r.addView(icon,ip);LinearLayout info=new LinearLayout(getActivity());info.setOrientation(LinearLayout.VERTICAL);info.setLayoutParams(new LinearLayout.LayoutParams(0,-2,1));TextView d=new TextView(getActivity());if(e.m!=null)d.setText(String.format(Locale.FRANCE,"Poids · %.1f kg",e.m.weight));else if(e.w!=null)d.setText("Eau · "+water(e.w.amountMl));else{String s=e.s.type+" · "+e.s.durationMinutes+" min";if(e.s.type.equals("Course")&&e.s.distanceKm>0)s+=String.format(Locale.FRANCE," · %.2f km",e.s.distanceKm);d.setText(s);}d.setTextSize(15);d.setTextColor(Color.rgb(71,85,105));info.addView(d);TextView time=new TextView(getActivity());time.setText("Mesuré à "+tf.format(new java.util.Date(e.time))+" · "+TimeZone.getDefault().getID());time.setTextSize(12);time.setTextColor(Color.rgb(100,116,139));info.addView(time);r.addView(info);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.bottomMargin=dp(7);list.addView(r,p);}
 private void editWeight(WeightDatabase.Measurement m){LinearLayout f=form();EditText v=new EditText(getActivity());v.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);v.setText(String.format(Locale.FRANCE,"%.1f",m.weight));f.addView(v);Calendar c=at(m.measuredAt);timePicker(f,c);new AlertDialog.Builder(getActivity()).setTitle("Modifier le poids · "+m.date).setView(f).setPositiveButton("Enregistrer",(d,w)->{try{double n=Double.parseDouble(v.getText().toString().trim().replace(',','.'));if(!WeightDatabase.isValidWeight(n))throw new IllegalArgumentException();db.save(m.date,n,c.getTimeInMillis());render();}catch(Exception x){Toast.makeText(getActivity(),"Poids invalide.",Toast.LENGTH_SHORT).show();}}).setNegativeButton("Annuler",null).show();}
 private void editWater(WeightDatabase.WaterEvent e){LinearLayout f=form();EditText v=new EditText(getActivity());v.setInputType(InputType.TYPE_CLASS_NUMBER);v.setText(String.valueOf(e.amountMl));f.addView(v);Calendar c=at(e.createdAt);timePicker(f,c);new AlertDialog.Builder(getActivity()).setTitle("Modifier l’eau · "+e.date).setView(f).setPositiveButton("Enregistrer",(d,w)->{try{int n=Integer.parseInt(v.getText().toString().trim());if(!WeightDatabase.isValidWaterAmount(n))throw new IllegalArgumentException();db.updateWaterEvent(e.id,n,c.getTimeInMillis());render();}catch(Exception x){Toast.makeText(getActivity(),"Quantité invalide (1 à 10 000 ml).",Toast.LENGTH_SHORT).show();}}).setNegativeButton("Annuler",null).show();}
 private void editSport(WeightDatabase.SportEvent e){LinearLayout f=form();RadioGroup g=new RadioGroup(getActivity());g.setOrientation(RadioGroup.VERTICAL);int sel=-1;for(String n:new String[]{"Yoga","Course","Escalade","Workout"}){RadioButton b=new RadioButton(getActivity());b.setText(n);b.setId(View.generateViewId());g.addView(b);if(n.equals(e.type))sel=b.getId();}g.check(sel);f.addView(g);EditText dur=new EditText(getActivity());dur.setHint("Durée en minutes");dur.setInputType(InputType.TYPE_CLASS_NUMBER);dur.setText(String.valueOf(e.durationMinutes));f.addView(dur);EditText dist=new EditText(getActivity());dist.setHint("Distance en km (course)");dist.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);if(e.distanceKm>0)dist.setText(String.valueOf(e.distanceKm));f.addView(dist);Calendar c=at(e.createdAt);timePicker(f,c);new AlertDialog.Builder(getActivity()).setTitle("Modifier le sport · "+e.date).setView(f).setPositiveButton("Enregistrer",(d,w)->{try{RadioButton b=f.findViewById(g.getCheckedRadioButtonId());String type=b.getText().toString();int mins=Integer.parseInt(dur.getText().toString().trim());double km=type.equals("Course")&&!dist.getText().toString().trim().isEmpty()?Double.parseDouble(dist.getText().toString().trim().replace(',','.')):0;if(!WeightDatabase.isValidSport(type,mins,km))throw new IllegalArgumentException();db.updateSportEvent(e.id,type,mins,km,c.getTimeInMillis());render();}catch(Exception x){Toast.makeText(getActivity(),"Vérifiez la durée et la distance.",Toast.LENGTH_SHORT).show();}}).setNegativeButton("Annuler",null).show();}
 private LinearLayout form(){LinearLayout f=new LinearLayout(getActivity());f.setOrientation(LinearLayout.VERTICAL);f.setPadding(dp(20),dp(8),dp(20),0);return f;}
 private void timePicker(LinearLayout f,Calendar c){TextView t=new TextView(getActivity());t.setTextSize(16);t.setTextColor(Color.rgb(20,36,58));t.setPadding(0,dp(12),0,dp(12));Runnable update=()->t.setText("Heure · "+tf.format(c.getTime())+" ("+TimeZone.getDefault().getID()+")");update.run();t.setOnClickListener(v->new TimePickerDialog(getActivity(),(p,h,m)->{c.set(Calendar.HOUR_OF_DAY,h);c.set(Calendar.MINUTE,m);c.set(Calendar.SECOND,0);c.set(Calendar.MILLISECOND,0);update.run();},c.get(Calendar.HOUR_OF_DAY),c.get(Calendar.MINUTE),true).show());f.addView(t);}
 private Calendar at(long t){Calendar c=Calendar.getInstance();c.setTimeInMillis(t);return c;}
 private String dateLabel(String raw){try{SimpleDateFormat f=new SimpleDateFormat("yyyy-MM-dd",Locale.US);f.setTimeZone(TimeZone.getDefault());return new SimpleDateFormat("EEEE d MMMM yyyy",Locale.FRANCE).format(f.parse(raw));}catch(Exception e){return raw;}}
 private String water(int ml){return ml>=1000&&ml%1000==0?ml/1000+" L ("+ml+" ml)":ml+" ml";}
 private int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}
}