package fr.bbodin.courbedepoids;
import android.content.Context;import android.graphics.Canvas;import android.graphics.Paint;import android.util.AttributeSet;import android.view.View;import java.text.SimpleDateFormat;import java.util.Calendar;import java.util.HashMap;import java.util.List;import java.util.Locale;import java.util.Map;
public class SportChartView extends View{
 private final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);private List<WeightDatabase.SportEvent> events;private int days=7;private int endOffsetDays=0;
 public SportChartView(Context c){super(c);}public SportChartView(Context c,AttributeSet a){super(c,a);}public SportChartView(Context c,AttributeSet a,int d){super(c,a,d);}public void setData(List<WeightDatabase.SportEvent> e,int n,int offsetDays){events=e;days=Math.max(3,n);endOffsetDays=offsetDays;invalidate();}private float dp(float n){return n*getResources().getDisplayMetrics().density;}
 @Override protected void onDraw(Canvas c){super.onDraw(c);if(events==null||events.isEmpty()){empty(c,"Aucune activité sportive enregistrée");return;}Calendar today=Calendar.getInstance();clear(today);Calendar end=(Calendar)today.clone();end.add(Calendar.DAY_OF_YEAR,-endOffsetDays);Calendar start=(Calendar)end.clone();start.add(Calendar.DAY_OF_YEAR,-(days-1));SimpleDateFormat f=new SimpleDateFormat("yyyy-MM-dd",Locale.US);Map<String,Integer> totals=new HashMap<>();for(WeightDatabase.SportEvent e:events)if(e.date.compareTo(f.format(start.getTime()))>=0&&e.date.compareTo(f.format(end.getTime()))<=0){Integer old=totals.get(e.date);totals.put(e.date,(old==null?0:old)+e.durationMinutes);}boolean any=false;for(Integer n:totals.values())if(n>0){any=true;break;}if(!any){empty(c,"Aucune activité sur cette période");return;}
 float l=dp(43),r=getWidth()-dp(8),t=dp(18),b=getHeight()-dp(34);if(r<=l||b<=t)return;int max=0;for(Integer n:totals.values())max=Math.max(max,n);int scale=Math.max(60,(int)Math.ceil(max/60.0)*60);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(1));p.setColor(0xFFE4EAF2);for(int i=0;i<=4;i++){float y=t+(b-t)*i/4f;c.drawLine(l,y,r,y,p);}p.setStyle(Paint.Style.FILL);p.setColor(0xFF7A8798);p.setTextSize(dp(10));for(int i=0;i<=4;i++){float y=t+(b-t)*i/4f,mins=scale*(4-i)/4f;c.drawText(mins>=60?String.format(Locale.FRANCE,"%.0f h",mins/60):String.format(Locale.FRANCE,"%.0f min",mins),0,y+dp(4),p);}
 float slot=(r-l)/days,w=Math.max(dp(2),Math.min(dp(22),slot*.62f));Calendar day=(Calendar)start.clone();SimpleDateFormat lab=new SimpleDateFormat("dd/MM",Locale.FRANCE);for(int i=0;i<days;i++){String key=f.format(day.getTime());int n=totals.containsKey(key)?totals.get(key):0;float x=l+slot*(i+.5f),y=b-(b-t)*n/(float)scale;p.setStyle(Paint.Style.FILL);p.setColor(n>0?0xFF147BEF:0xFFE2EAF4);if(n>0)c.drawRoundRect(x-w/2,y,x+w/2,b,dp(4),dp(4),p);int labelStep=days<=7?1:days<=30?5:days<=90?15:60;if(i%labelStep==0||i==days-1){p.setColor(0xFF7A8798);p.setTextSize(dp(9));String s=lab.format(day.getTime());float sw=p.measureText(s);c.drawText(s,Math.max(l,Math.min(x-sw/2,r-sw)),b+dp(25),p);}day.add(Calendar.DAY_OF_YEAR,1);}}
 private void clear(Calendar c){c.set(Calendar.HOUR_OF_DAY,0);c.set(Calendar.MINUTE,0);c.set(Calendar.SECOND,0);c.set(Calendar.MILLISECOND,0);}private void empty(Canvas c,String s){p.setStyle(Paint.Style.FILL);p.setColor(0xFF718198);p.setTextSize(dp(13));p.setTextAlign(Paint.Align.CENTER);c.drawText(s,getWidth()/2f,getHeight()/2f,p);p.setTextAlign(Paint.Align.LEFT);}
}